### ISSUE TITLE
Create a Card component

### ISSUE THREAD

**Issue by dongwookaugust** [daniel-august-mentorship/Demo-School#6]
Create a reusable card component, similar to mockup below

![Image](https://github.com/daniel-august-mentorship/Demo-School/assets/6497134/9c7e851c-1c70-4b53-bc79-4f042695058f)

AC (Acceptance Criteria)

- [x]  Set the size to be 260px by 160px
- [x] Border 2 px, rounded.
- [x] The title (Daily login) should be configurable and font color to #666666
- [x] The icon and icon color should be configurable, default cyan #134F5C
- [x] The content (150) should be configurable
- [x] the arrow should be either up or down. 
- [x] When the arrow is up, it should be green #009E0F
- [x] When the arrow is down, it should be red #CC0000
- [x] The label (Since last month) should be configurable and font color #666666

**Comment by danielbibal** [comment]
@dongwookaugust  I am getting an error when starting the application in `card` branch.

<img width="1273" alt="image" src="https://github.com/daniel-august-mentorship/Demo-School/assets/6497134/989493d6-5941-4a6c-bd63-54459c4dcd6e">

this is because github is tracking `Pages.css` and you used `pages.css`. To fix this, we need to rename the tracking in github as well. You can do this using the move command. Navigate to `/src/pages` then run the command. Commit the changes after

```
git mv Pages.css pages.css
```
